<?php
class Helper_Cities
{
    public static $cities = array(
        /*
        'ID_old' => array(
            'Ambon',
            'Balikpapan',
            'Banda Aceh',
            'Bandar Lampung',
            'Bandung',
            'Banjar',
            'Banjarbaru',
            'Banjarmasin',
            'Batam',
            'Batu',
            'Bau-Bau',
            'Bekasi',
            'Bengkulu',
            'Bima',
            'Binjai',
            'Bitung',
            'Blitar',
            'Bogor',
            'Bontang',
            'Bukittinggi',
            'Cilegon',
            'Cimahi',
            'Cirebon',
            'Denpasar',
            'Depok',
            'Dumai',
            'Gorontalo',
            'Gunung Sitoli',
            'Jakarta',
            'Jambi',
            'Jayapura',
            'Kediri',
            'Kendari',
            'Klaten',
            'Kotamobagu',
            'Kupang',
            'Langsa',
            'Lhokseumawe',
            'Lubuklinggau',
            'Madiun',
            'Magelang',
            'Makasar',
            'Malang',
            'Manado',
            'Mataram',
            'Medan',
            'Metro',
            'Mojokerto',
            'Padang',
            'Padang Sidempuan',
            'Pagaralam',
            'Palangkaraya',
            'Palembang',
            'Palopo',
            'Palu',
            'Pangkalpinang',
            'Parepare',
            'Pasuruan',
            'Payakumbuh',
            'Pekalongan',
            'Pekanbaru',
            'Pematangsiantar',
            'Pontianak',
            'Prabumulih',
            'Probolinggo',
            'Purwokerto',
            'Salatiga',
            'Samarinda',
            'Semarang',
            'Serang',
            'Singkawang',
            'Solo',
            'Sorong',
            'Sukabumi',
            'Surabaya',
            'Tangerang',
            'Tanjung Balai',
            'Tanjungpinang',
            'Tarakan',
            'Tasikmalaya',
            'Tebingtinggi',
            'Tegal',
            'Ternate',
            'Yogyakarta',
        ),
        */
        'ID' => array(
            'Ambon',
            'Balikpapan',
            'Banda Aceh',
            'Bandar Lampung',
            'Bandung',
            'Banjarmasin',
            'Batam',
            'Bekasi',
            'Bengkulu',
            'Bogor',
            'Bontang',
            'Cilacap',
            'Cilegon',
            'Cirebon',
            'Denpasar',
            'Depok',
            'Gorontalo',
            'Jakarta',
            'Jayapura',
            'Jember',
            'Karawang',
            'Kediri',
            'Kendari',
            'Kupang',
            'Madiun',
            'Magelang',
            'Malang',
            'Manado',
            'Mataram',
            'Medan',
            'Mojokerto',
            'Nabire',
            'Padang',
            'Palangkaraya',
            'Palembang',
            'Palu',
            'Pandaan',
            'Pangkal Pinang',
            'Pekanbaru',
            'Pontianak',
            'Probolinggo',
            'Samarinda',
            'Semarang',
            'Solo',
            'Sorong',
            'Sukabumi',
            'Surabaya',
            'Tangerang',
            'Tanjung Pandan',
            'Tanjung Pinang',
            'Tarakan',
            'Ternate',
            'Timika',
            'Ujungpandang',
            'Yogyakarta',
        ),
        'FOO' => array(
            'Foo 1',
            'Foo 2',
            'Foo 3',
        ),
        'Some Country' => array(
            'Some City',
        ),
        'Shipping Country 3' => array(
            'Shipping City 3',
        ),
        'Shipping Country 7' => array(
            'Shipping City 7',
        ),
    );

    public static $cities_id = array(
        'Ambon' => 'AMQ10000',
        'Balikpapan' => 'BPN10000',
        'Banda Aceh' => 'BTJ10000',
        'Bandar Lampung' => 'TKG10000',
        'Bandung' => 'BDO10000',
        'Banjarmasin' => 'BDJ10000',
        'Batam' => 'BTH10000',
        'Bekasi' => 'BKI10000',
        'Bengkulu' => 'BKS10000',
        'Bogor' => 'BOO10000',
        'Bontang' => 'BTG10000',
        'Cilacap' => 'CXP10000',
        'Cilegon' => 'CLG10000',
        'Cirebon' => 'CBN10000',
        'Denpasar' => 'DPS10000',
        'Depok' => 'DPK10000',
        'Gorontalo' => 'GTO10000',
        'Jakarta' => 'CGK10000',
        'Jayapura' => 'DJJ10000',
        'Jember' => 'JBR10000',
        'Karawang' => 'KRW10000',
        'Kediri' => 'KDR10000',
        'Kendari' => 'KDI10000',
        'Kupang' => 'KOE10000',
        'Madiun' => 'MDN10000',
        'Magelang' => 'MGL10000',
        'Malang' => 'MXG10000',
        'Manado' => 'MDC10000',
        'Mataram' => 'AMI10000',
        'Medan' => 'MES10000',
        'Mojokerto' => 'MJK10000',
        'Nabire' => 'NBX10000',
        'Padang' => 'PDG10000',
        'Palangkaraya' => 'PKY10000',
        'Palembang' => 'PLM10000',
        'Palu' => 'PLW10000',
        'Pandaan' => 'PDN10000',
        'Pangkal Pinang' => 'PGK10000',
        'Pekanbaru' => 'PKU10000',
        'Pontianak' => 'PNK10000',
        'Probolinggo' => 'PBL10000',
        'Samarinda' => 'SMD10000',
        'Semarang' => 'SRG10000',
        'Solo' => 'SOC10000',
        'Sorong' => 'SOQ10000',
        'Sukabumi' => 'SMI10000',
        'Surabaya' => 'SUB10000',
        'Tangerang' => 'TGR10000',
        'Tanjung Pandan' => 'TJQ10000',
        'Tanjung Pinang' => 'TNJ10000',
        'Tarakan' => 'TRK10000',
        'Ternate' => 'TTE10000',
        'Timika' => 'TIM10000',
        'Ujungpandang' => 'UPG10000',
        'Yogyakarta' => 'JOG10000',
    );

    static function getCitiesByCountry($controller, $country)
    {
        if (isset(self::$cities[$country])) {
            return self::$cities[$country];
        }
        return array();
    }
}
